name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.2.0-ukuya.beta.10
repository: https://github.com/zino-app/graphql-flutter/tree/main/packages/graphql
issue_tracker: https://github.com/zino-hofmann/graphql-flutter/issues
publish_to: https://flutterpackages.ukuya.net/

dependencies:
  meta: ^1.9.1
  path: ^1.8.3
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  gql_http_link: ^1.0.1
  gql_transform_link: ^1.0.0
  gql_error_link: ^1.0.0
  gql_dedupe_link: ^2.0.3+1
  hive: ^2.2.3
  normalize: ^0.8.2+1
  http: ^1.1.0
  collection: ^1.17.2
  web_socket_channel: ^2.4.0
  stream_channel: ^2.1.1
  rxdart: ^0.27.7
  uuid: ^4.1.0

dev_dependencies:
  async: ^2.11.0
  mockito: ^5.4.2
  test: ^1.24.9
  coverage: ^1.7.1
  http_parser: ^4.0.2
  lints: ^3.0.0

environment:
  sdk: '>=2.15.0 <4.0.0'
